name: easy_ussd
description: Aplicacion para facilitar el uso de los códigos USSD de ETECSA para la consulta de datos, compra de planes y pequetes de datos y similares.

publish_to: 'none'

version: 1.0.0-BETA.20220915

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.5
  clean_core: ^1.3.3-RELEASE.20220407
  tuple: ^2.0.0

  # ussd / calls
  ussd_advanced: ^1.0.0

  #Notifications & Dialogs
  awesome_dialog: ^3.0.1
  loader_overlay: ^2.0.10

  #S
  flutter_native_splash: ^2.2.9

  cupertino_icons: ^1.0.5

  #DB
  objectbox: ^1.6.0
  objectbox_flutter_libs: ^1.6.0
  path_provider: ^2.0.11
  flat_buffers: ^2.0.5
  clean_repo_objectbox: ^1.0.0-RELEASE.20220407

  #Utils
  permission_handler: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0
  #flutter_app_name: ^0.1.1

#configuration of splash screen, if something change, run: `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  android_12:
    image: assets/app_splash.png
    color: "#42a5f5"
    icon_background_color: "#eeeeee"
  image: assets/app_splash.png
  color: "#42a5f5"

#configuration of flutter_icons, if something change, run: `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

#configuration of flutter_app_name, if something change, run: `flutter pub run flutter_app_name`
#flutter_app_name:
#  name: "Maple"


  #DB code generation
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/app_splash.png

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Variable.ttf
          weight: 400
