name: easy_ussd
description: Aplicacion para facilitar el uso de los códigos USSD de ETECSA para la consulta de datos, compra de planes y pequetes de datos y similares.

publish_to: 'none'

version: 1.0.0-BETA.20220915

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.5
  clean_core: ^1.3.3-RELEASE.20220407
  tuple: ^2.0.0

  # ussd / calls
  ussd_advanced: ^1.0.0

  #Notifications & Dialogs
  awesome_dialog: ^3.0.1
  loader_overlay: ^2.0.10

  cupertino_icons: ^1.0.5

  #DB
  objectbox: ^1.6.0
  objectbox_flutter_libs: ^1.6.0
  path_provider: ^2.0.11
  flat_buffers: ^2.0.5
  clean_repo_objectbox: ^1.0.0-RELEASE.20220407

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.0

flutter:

  uses-material-design: true

