// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/repo/b_entities/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8195781853182384524),
      name: 'USSDExpandedGroupEntity',
      lastPropertyId: const IdUid(4, 1194776785211634525),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1182637103974531329),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 7456535921171101739),
            name: 'expanded',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1194776785211634525),
            name: 'groupKey',
            type: 9,
            flags: 2080,
            indexId: const IdUid(3, 9217226278114177738))
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 8629747884124646899),
      name: 'USSDFavoriteActionEntity',
      lastPropertyId: const IdUid(5, 5076049528668474780),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4433343923635866209),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2076292997254348047),
            name: 'actionKey',
            type: 9,
            flags: 2080,
            indexId: const IdUid(2, 4944760352389094358)),
        ModelProperty(
            id: const IdUid(3, 6692542786471608608),
            name: 'favorite',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5076049528668474780),
            name: 'lastUpdatedOn',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 8629747884124646899),
      lastIndexId: const IdUid(3, 9217226278114177738),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [7015419465327010104],
      retiredPropertyUids: const [1017336373897191586, 6376580609029143801],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    USSDExpandedGroupEntity: EntityDefinition<USSDExpandedGroupEntity>(
        model: _entities[0],
        toOneRelations: (USSDExpandedGroupEntity object) => [],
        toManyRelations: (USSDExpandedGroupEntity object) => {},
        getId: (USSDExpandedGroupEntity object) => object.id,
        setId: (USSDExpandedGroupEntity object, int id) {
          object.id = id;
        },
        objectToFB: (USSDExpandedGroupEntity object, fb.Builder fbb) {
          final groupKeyOffset = fbb.writeString(object.groupKey);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addBool(2, object.expanded);
          fbb.addOffset(3, groupKeyOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = USSDExpandedGroupEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              groupKey: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              expanded: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 8, false));

          return object;
        }),
    USSDFavoriteActionEntity: EntityDefinition<USSDFavoriteActionEntity>(
        model: _entities[1],
        toOneRelations: (USSDFavoriteActionEntity object) => [],
        toManyRelations: (USSDFavoriteActionEntity object) => {},
        getId: (USSDFavoriteActionEntity object) => object.id,
        setId: (USSDFavoriteActionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (USSDFavoriteActionEntity object, fb.Builder fbb) {
          final actionKeyOffset = fbb.writeString(object.actionKey);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, actionKeyOffset);
          fbb.addBool(2, object.favorite);
          fbb.addInt64(4, object.lastUpdatedOn.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = USSDFavoriteActionEntity(
              actionKey: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              lastUpdatedOn: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)),
              favorite:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [USSDExpandedGroupEntity] entity fields to define ObjectBox queries.
class USSDExpandedGroupEntity_ {
  /// see [USSDExpandedGroupEntity.id]
  static final id =
      QueryIntegerProperty<USSDExpandedGroupEntity>(_entities[0].properties[0]);

  /// see [USSDExpandedGroupEntity.expanded]
  static final expanded =
      QueryBooleanProperty<USSDExpandedGroupEntity>(_entities[0].properties[1]);

  /// see [USSDExpandedGroupEntity.groupKey]
  static final groupKey =
      QueryStringProperty<USSDExpandedGroupEntity>(_entities[0].properties[2]);
}

/// [USSDFavoriteActionEntity] entity fields to define ObjectBox queries.
class USSDFavoriteActionEntity_ {
  /// see [USSDFavoriteActionEntity.id]
  static final id = QueryIntegerProperty<USSDFavoriteActionEntity>(
      _entities[1].properties[0]);

  /// see [USSDFavoriteActionEntity.actionKey]
  static final actionKey =
      QueryStringProperty<USSDFavoriteActionEntity>(_entities[1].properties[1]);

  /// see [USSDFavoriteActionEntity.favorite]
  static final favorite = QueryBooleanProperty<USSDFavoriteActionEntity>(
      _entities[1].properties[2]);

  /// see [USSDFavoriteActionEntity.lastUpdatedOn]
  static final lastUpdatedOn = QueryIntegerProperty<USSDFavoriteActionEntity>(
      _entities[1].properties[3]);
}
